//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GatewayHSSP {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GatewayHSSP.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 关闭服务 的本地化字符串。
        /// </summary>
        internal static string CloseServer {
            get {
                return ResourceManager.GetString("CloseServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统配置 的本地化字符串。
        /// </summary>
        internal static string MainServebtnConfig {
            get {
                return ResourceManager.GetString("MainServebtnConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开启操作 的本地化字符串。
        /// </summary>
        internal static string MainServebtnLock {
            get {
                return ResourceManager.GetString("MainServebtnLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭操作 的本地化字符串。
        /// </summary>
        internal static string MainServebtnLockOpen {
            get {
                return ResourceManager.GetString("MainServebtnLockOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 鸿睿物联通讯平台 的本地化字符串。
        /// </summary>
        internal static string MainServer {
            get {
                return ResourceManager.GetString("MainServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动服务 的本地化字符串。
        /// </summary>
        internal static string MainServerbtnMonitor {
            get {
                return ResourceManager.GetString("MainServerbtnMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看设备 的本地化字符串。
        /// </summary>
        internal static string MainServerbtnOnlySel {
            get {
                return ResourceManager.GetString("MainServerbtnOnlySel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 简体中文 的本地化字符串。
        /// </summary>
        internal static string MainServercmbLanguage_0 {
            get {
                return ResourceManager.GetString("MainServercmbLanguage_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 English 的本地化字符串。
        /// </summary>
        internal static string MainServercmbLanguage_1 {
            get {
                return ResourceManager.GetString("MainServercmbLanguage_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 天 的本地化字符串。
        /// </summary>
        internal static string MainServerlabDay {
            get {
                return ResourceManager.GetString("MainServerlabDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时 的本地化字符串。
        /// </summary>
        internal static string MainServerlabHour {
            get {
                return ResourceManager.GetString("MainServerlabHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 监听IP: 的本地化字符串。
        /// </summary>
        internal static string MainServerlabIP {
            get {
                return ResourceManager.GetString("MainServerlabIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语言: 的本地化字符串。
        /// </summary>
        internal static string MainServerlabLanguage {
            get {
                return ResourceManager.GetString("MainServerlabLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分 的本地化字符串。
        /// </summary>
        internal static string MainServerlabMinutes {
            get {
                return ResourceManager.GetString("MainServerlabMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 离线数: 的本地化字符串。
        /// </summary>
        internal static string MainServerlaboffLine {
            get {
                return ResourceManager.GetString("MainServerlaboffLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在线数: 的本地化字符串。
        /// </summary>
        internal static string MainServerlabOnline {
            get {
                return ResourceManager.GetString("MainServerlabOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 端口: 的本地化字符串。
        /// </summary>
        internal static string MainServerlabPort {
            get {
                return ResourceManager.GetString("MainServerlabPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运行计时： 的本地化字符串。
        /// </summary>
        internal static string MainServerlabTime {
            get {
                return ResourceManager.GetString("MainServerlabTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动服务 的本地化字符串。
        /// </summary>
        internal static string OpenServer {
            get {
                return ResourceManager.GetString("OpenServer", resourceCulture);
            }
        }
    }
}
